name: Build iOS Dylib

on: [push]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install ldid

      - name: Compile for iOS
        run: |
          # Locate the iOS SDK on the runner
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          
          # Compile specifically for ARM64 iOS devices
          clang -dynamiclib -isysroot $SDK_PATH \
          -arch arm64 \
          -miphoneos-version-min=14.0 \
          -o tracker.dylib tracker.c -lcurl

      - name: Pseudo-sign dylib
        run: ldid -S tracker.dylib

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-tracker-dylib
          path: tracker.dylib
