name: Build iOS Dylib

on: [push]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ldid
        run: brew install ldid

      - name: Compile for iOS
        run: |
          # Use xcrun to find the specific iPhoneOS SDK
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          
          # Force the target to arm64-apple-ios
          clang -dynamiclib \
          -target arm64-apple-ios14.0 \
          -isysroot "$SDK_PATH" \
          -o tracker.dylib tracker.c \
          -lcurl \
          -framework Foundation

      - name: Pseudo-sign dylib
        run: ldid -S tracker.dylib

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ios-dylib
          path: tracker.dylib
